/*
 * JSP generated by Resin Professional 4.0.48 (built Wed, 17 Feb 2016 11:03:24 PST)
 */

package _jsp._cdrquery;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _howtouse__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, null, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -8002497470487589159L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("cdrquery/howtouse.jsp"), 713443240551343266L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string0;
  static {
    _jsp_string0 = "<!DOCTYPE html>\r\n\r\n<html>\r\n<head>\r\n	<meta charset=\"UTF-8\">\r\n	<title>\u4f7f\u7528\u8bf4\u660e</title>\r\n</head>\r\n<body>\r\n	<p style=\"font-size:14px;font-weight:bold\" align=\"center\">\u4f7f\u7528\u8bf4\u660e</p>\r\n	<ul >\r\n		<li>\u70b9\u51fb <img src=\"images/yesterday.jpg\" border=\"0\" align=\"middle\"> ,\u67e5\u8be2\u6628\u59290\u70b9\u5230\u5f53\u524d\u65f6\u95f4\u7684\u6570\u636e</li>\r\n		<li>\u70b9\u51fb <img src=\"images/lastday.jpg\" border=\"0\" align=\"middle\"> ,\u67e5\u8be2\u524d\u59290\u70b9\u5230\u5f53\u524d\u65f6\u95f4\u7684\u6570\u636e</li>\r\n		<li>\u70b9\u51fb <img src=\"images/chart.jpg\" border=\"0\" align=\"middle\"> ,\u5bf9\u67e5\u8be2\u7ed3\u679c\u8fdb\u884c\u591a\u7ef4\u5ea6\u7edf\u8ba1</li>\r\n		<li>\u70b9\u51fb <img src=\"images/location.jpg\" border=\"0\" align=\"middle\"> ,\u67e5\u770b\u7528\u6237\u5f53\u524d\u767b\u8bb0\u5c0f\u533a\u5730\u56fe\u4f4d\u7f6e</li>\r\n		<li>\u53cc\u51fb\u8868\u683c\u6570\u636e\uff0c\u5c06\u5f39\u51fa\u7a97\u53e3\u663e\u793a\u8bb0\u5f55\u7684\u8be6\u7ec6\u5185\u5bb9</li>\r\n		<li>\u5f53\u67e5\u8be2\u663e\u793a\u6709\u8bb0\u5f55\uff0c\u4f46\u8868\u683c\u4e2d\u663e\u793a\u4e3a\u7a7a\u65f6\uff0c\u8bf7\u5c06\u9875\u7801\u6539\u62101\u5e76\u56de\u8f66\u5373\u53ef</li>\r\n	</ul>\r\n</body>\r\n</html>".toCharArray();
  }
}
